-- ==========================================
-- Amazon Sales Analysis SQL Queries
-- Author: Anmol Arora
-- Project: Amazon Sales Analysis
-- ==========================================

-- 1. Total Revenue
SELECT SUM(total_amount) AS TotalRevenue
FROM amazon_orders;

-- 2. Total Orders
SELECT COUNT(order_id) AS TotalOrders
FROM amazon_orders;

-- 3. Average Order Value
SELECT AVG(total_amount) AS AverageOrderValue
FROM amazon_orders;

-- 4. Total Customers
SELECT COUNT(customer_id) AS TotalCustomers
FROM amazon_customers;

-- 5. Total Products
SELECT COUNT(product_id) AS TotalProducts
FROM amazon_products;

-- 6. Top 10 Customers by Total Spending
SELECT
    c.customer_name,
    SUM(o.total_amount) AS TotalSpent
FROM amazon_orders o
JOIN amazon_customers c
ON o.customer_id = c.customer_id
GROUP BY c.customer_name
ORDER BY TotalSpent DESC
LIMIT 10;

-- 7. Top 10 Best Selling Products
SELECT
    p.product_name,
    SUM(o.quantity) AS TotalQuantitySold
FROM amazon_orders o
JOIN amazon_products p
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY TotalQuantitySold DESC
LIMIT 10;

-- 8. Revenue by Product Category
SELECT
    p.category,
    SUM(o.total_amount) AS Revenue
FROM amazon_orders o
JOIN amazon_products p
ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY Revenue DESC;

-- 9. Orders by Status
SELECT
    order_status,
    COUNT(*) AS TotalOrders
FROM amazon_orders
GROUP BY order_status
ORDER BY TotalOrders DESC;

-- 10. Monthly Sales
SELECT
    MONTH(order_date) AS Month,
    SUM(total_amount) AS Revenue
FROM amazon_orders
GROUP BY MONTH(order_date)
ORDER BY Month;

-- 11. Average Product Price by Category
SELECT
    category,
    AVG(price) AS AveragePrice
FROM amazon_products
GROUP BY category
ORDER BY AveragePrice DESC;

-- 12. Customers with More Than 3 Orders
SELECT
    c.customer_name,
    COUNT(o.order_id) AS TotalOrders
FROM amazon_customers c
JOIN amazon_orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
HAVING COUNT(o.order_id) > 3
ORDER BY TotalOrders DESC;

-- 13. Highest Value Order
SELECT *
FROM amazon_orders
ORDER BY total_amount DESC
LIMIT 1;

-- 14. Products Never Ordered
SELECT
    product_name
FROM amazon_products
WHERE product_id NOT IN
(
    SELECT DISTINCT product_id
    FROM amazon_orders
);

-- 15. Top 5 Most Expensive Products
SELECT
    product_name,
    price
FROM amazon_products
ORDER BY price DESC
LIMIT 5;

-- 16. Revenue Generated by Each Customer
SELECT
    c.customer_name,
    SUM(o.total_amount) AS Revenue
FROM amazon_customers c
JOIN amazon_orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY Revenue DESC;

-- 17. Rank Customers by Revenue
SELECT
    c.customer_name,
    SUM(o.total_amount) AS Revenue,
    RANK() OVER(ORDER BY SUM(o.total_amount) DESC) AS RevenueRank
FROM amazon_customers c
JOIN amazon_orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name;

-- 18. Revenue by City
SELECT
    c.city,
    SUM(o.total_amount) AS Revenue
FROM amazon_customers c
JOIN amazon_orders o
ON c.customer_id = o.customer_id
GROUP BY c.city
ORDER BY Revenue DESC;

-- 19. Revenue by Payment Method
SELECT
    payment_method,
    SUM(total_amount) AS Revenue
FROM amazon_orders
GROUP BY payment_method
ORDER BY Revenue DESC;

-- 20. Top Selling Product in Each Category
SELECT
    category,
    product_name,
    TotalSold
FROM
(
    SELECT
        p.category,
        p.product_name,
        SUM(o.quantity) AS TotalSold,
        RANK() OVER
        (
            PARTITION BY p.category
            ORDER BY SUM(o.quantity) DESC
        ) AS RankNo
    FROM amazon_orders o
    JOIN amazon_products p
    ON o.product_id = p.product_id
    GROUP BY p.category, p.product_name
) AS RankedProducts
WHERE RankNo = 1;
